crontab:
  processCurrencyRate: "*/1 * * * * *"
spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    virtual-host: /
    template:
      routing-key: rate
  data:
    mongodb:
      host: localhost
      port: 28017
      database: rates
  security:
    oauth2:
      client:
        registration:
          keycloak:
            client-id: login-app
            authorization-grant-type: authorization_code
            scope: openid
        provider:
          keycloak:
            issuer-uri: http://localhost:8085/realms/SpringBootKeycloak
            user-name-attribute: preferred_username
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8085/realms/SpringBootKeycloak
server:
  port: 8081