
spring:
  rabbitmq:
    addresses: ${RABBIT_ADDRESSES:localhost:5671}
    username: ${RABBIT_USERNAME:guest}
    password: ${RABBIT_PASSWORD:guest}

  liquibase:
    change-log: liquibase/db.changelog.xml

  datasource:
    url: jdbc:mysql://${MYSQL_ADDRESSES:localhost:3305}/${MYSQL_DATABASE:rates}
    username: ${MYSQL_USER:root}
    password: ${MYSQL_PASSWORD:root}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    show-sql: true
    open-in-view: false

  security:
    oauth2:
      resource-server:
        jwt:
          issuer-uri: http://${KEYCLOAK_ADDRESSES:localhost:8078}/realms/RATES
          jwk-set-uri: ${spring.security.oauth2.resource-server.jwt.issuer-uri}/protocol/openid-connect/certs

jwt:
  auth:
    converter:
      resource-id: exchange-api
      principle-attribute: preferred_username

server:
  port: ${APP_PORT:8087}

app:
  async:
    threads: 3
  queue-name: send_email_data_queue