
spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    queue-name: send_email_data_queue

  liquibase:
    change-log: liquibase/db.changelog.xml

  datasource:
    url: jdbc:mysql://localhost:3309/rates
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    show-sql: true
    open-in-view: false

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/RATES
          jwk-set-uri: ${spring.security.oauth2.resourceserver.jwt.issuer-uri}/protocol/openid-connect/certs

jwt:
  auth:
    converter:
      resource-id: exchange-api
      principle-attribute: preferred_username

server:
  port: 8083

app:
  async:
    threads: 3